build_from:
  amd64: seafileltd/seafile-mc:latest
  aarch64: seafileltd/seafile-mc:latest
labels:
  io.hass.name: "Seafile"
  io.hass.description: "Self-hosted file sync and sharing with built-in MariaDB"
  io.hass.arch: "amd64|aarch64"
  io.hass.type: "addon"
  io.hass.version: "0.2.7"
